<a href="https://colab.research.google.com/github/spencer18001/Clustering-And-Dimensionality-Reduction---Deep-Dive/blob/main/0309.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Merging numpy arrays

### Lecture agenda

- Merging numpy arrays
  - Concatenations
  - Stacking

In [1]:
import numpy as np

##### Concatenations

In [2]:
# Merge 1D arrays

a = np.array([1, 2])
b = np.array([5, 6, 7, 8])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.concatenate((a, b))
c

Arr 1 : 
 [1 2]
Arr 2 : 
 [5 6 7 8]


array([1, 2, 5, 6, 7, 8])

In [3]:
# Merge, axis=0

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.concatenate((a, b), axis=0)
c

Arr 1 : 
 [[1 2]
 [3 4]]
Arr 2 : 
 [[5 6]
 [7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
# Merge, axis=1

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7,8]])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.concatenate((a, b), axis=1)
c

Arr 1 : 
 [[1 2]
 [3 4]]
Arr 2 : 
 [[5 6]
 [7 8]]


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [5]:
# Merge, axis=0

a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6]) # 嚴格要求 rank 要一致

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.concatenate((a, b), axis=0)
c

Arr 1 : 
 [[1 2]
 [3 4]]
Arr 2 : 
 [5 6]


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [6]:
# Merge, axis=0

a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

b = np.expand_dims(b, axis=0)

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.concatenate((a, b), axis=0)
c

Arr 1 : 
 [[1 2]
 [3 4]]
Arr 2 : 
 [[5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
### Concatenating multiple arrays

# Define three 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.array([[13, 14, 15], [16, 17, 18]])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))
print('Arr 3 : \n {}'.format(c))


d = np.concatenate((a, b, c), axis=0)
d

Arr 1 : 
 [[1 2 3]
 [4 5 6]]
Arr 2 : 
 [[ 7  8  9]
 [10 11 12]]
Arr 3 : 
 [[13 14 15]
 [16 17 18]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

##### Stacking

In [8]:
# Vertical stacking

a = np.array([1, 2])
b = np.array([3, 4])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.vstack((a, b))
c

Arr 1 : 
 [1 2]
Arr 2 : 
 [3 4]


array([[1, 2],
       [3, 4]])

In [9]:
# Vertical stacking

a = np.array([1, 2]) # 預設 1D array 為 row
b = np.array([[3, 4], [5, 6]])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.vstack((a, b))
c

Arr 1 : 
 [1 2]
Arr 2 : 
 [[3 4]
 [5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
# Column stacking

a = np.array([1,2,3]) # 預設 1D array 為 column
b = np.array([2,3,4])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))

c = np.column_stack((a,b))
c

Arr 1 : 
 [1 2 3]
Arr 2 : 
 [2 3 4]


array([[1, 2],
       [2, 3],
       [3, 4]])

In [11]:
# Column stacking

a = np.array([1,2,3])
b = np.array([2,3,4])
c = np.array([[10,20], [30, 40], [50, 60]])

print('Arr 1 : \n {}'.format(a))
print('Arr 2 : \n {}'.format(b))
print('Arr 3 : \n {}'.format(c))


d = np.column_stack((a,b,c))
d

Arr 1 : 
 [1 2 3]
Arr 2 : 
 [2 3 4]
Arr 3 : 
 [[10 20]
 [30 40]
 [50 60]]


array([[ 1,  2, 10, 20],
       [ 2,  3, 30, 40],
       [ 3,  4, 50, 60]])