<a href="https://colab.research.google.com/github/spencer18001/Clustering-And-Dimensionality-Reduction---Deep-Dive/blob/main/0310.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy datatypes

### Lecture agenda
- Datatypes
- Datatype conversions

Numpy array can contain only elements of one datatype.

In [1]:
import numpy as np

In [2]:
int_arr = np.array([1, 2, 3, 4], dtype=np.int64)

print(int_arr)
print(int_arr.dtype)

[1 2 3 4]
int64


`np.int32`: This is a 32-bit integer type. It can represent integer values from -2147483648 to 2147483647. It uses 32 bits of memory, which equals 4 bytes.

`np.int64`: This is a 64-bit integer type. It can represent integer values from -9223372036854775808 to 9223372036854775807. It uses 64 bits of memory, which equals 8 bytes.

In [3]:
int_arr = np.array([1, 2, 3, 4], dtype=np.int32)

print(int_arr)
print(int_arr.dtype)

[1 2 3 4]
int32


In [4]:
float_arr = np.array([1.5, 2.5, 3.5, 4.5], dtype=np.float64)

print(float_arr)
print(float_arr.dtype)

[1.5 2.5 3.5 4.5]
float64


In [5]:
bool_arr = np.array([True, False, True], dtype=np.bool_)

print(bool_arr)
print(bool_arr.dtype)

[ True False  True]
bool


##### Datatype conversion

In [6]:
# Integer to float
a = np.array([1, 2, 3, 4], dtype=np.int64)
print(a)
print(a.dtype)

b = a.astype(np.float64)
print(b)
print(b.dtype)

[1 2 3 4]
int64
[1. 2. 3. 4.]
float64


In [7]:
# We can not add float number to integer array (精度會遺失)
a = np.array([1, 2, 3, 4], dtype=np.int64)
print(a)

a[0] = 9.1

a

[1 2 3 4]


array([9, 2, 3, 4])

In [8]:
# Float to integer
a = np.array([1.1, 2, 3.9, 4], dtype=np.float64)
print(a)
print(a.dtype)

b = a.astype(np.int64)
print(b)
print(b.dtype)

[1.1 2.  3.9 4. ]
float64
[1 2 3 4]
int64


In [9]:
# Boolean to int
a = np.array([True, False, True, True, False], dtype=np.bool_)

print(a)
print(a.dtype)

# Convert the boolean array to an integer array
b = a.astype(np.int64)

print(b)
print(b.dtype)


[ True False  True  True False]
bool
[1 0 1 1 0]
int64
