<a href="https://colab.research.google.com/github/spencer18001/Clustering-And-Dimensionality-Reduction---Deep-Dive/blob/main/0306.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Operations on single numpy arrays

#### Lecture agenda

- Operations on 1-D and 2-D arrays

- Array reshaping

In [1]:
import numpy as np

##### Handling 1-D arrays


In [2]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [3]:
# Mathematical operations

# Square root of each element
print("Square root:", np.sqrt(arr1))

# Exponential (base e) of each element
print("Exponential:", np.exp(arr1))

# Log of each element
print("Log:", np.log(arr1))

Square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
Log: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [4]:
# Operations with scalars

# Adding a scalar to all elements in the array
print("Addition:", arr1 + 1)

# Multiplying all elements in the array by a scalar
print("Multiplication:", arr1 * 2)

# Comparison with a scalar
print("Greather than 2:", arr1 > 2)

Addition: [2 3 4 5 6 7]
Multiplication: [ 2  4  6  8 10 12]
Greather than 2: [False False  True  True  True  True]


In [5]:
# Aggregation functions

# Sum of elements
print("Sum:", np.sum(arr1))

# Average of elements
print("Average:", np.mean(arr1))

# Maximum element
print("Max:", np.max(arr1))

# Minimum element
print("Min:", np.min(arr1))

Sum: 21
Average: 3.5
Max: 6
Min: 1


In [6]:
# Sorting

arr3 = np.array([2,1,4,1,8])
arr3.sort()

print("Sorted:", arr3)

Sorted: [1 1 2 4 8]


##### 2-D arrays - basic operations

In [7]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
# Mathematical operations

# Square root of each element
print("Square root: \n", np.sqrt(arr1))

# Exponential (base e) of each element
print("Exponential: '\n", np.exp(arr1))

# Log of each element
print("Log: \n", np.log(arr1))

Square root: 
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
Exponential: '
 [[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
Log: 
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [10]:
# Working with scalars

# Adding a scalar to all elements in the array
print("Addition:\n", arr1 + 1)

# Multiplying all elements in the array by a scalar
print("Multiplication:\n", arr1 * 2)

# Multiplying all elements in the array by a scalar
print("Greather than 2:\n", arr1 > 2)

Addition:
 [[2 3 4]
 [5 6 7]]
Multiplication:
 [[ 2  4  6]
 [ 8 10 12]]
Greather than 2:
 [[False False  True]
 [ True  True  True]]


In [11]:
# Aggregation of the whole array

# Sum of elements
print("Sum:", np.sum(arr1))

# Average of elements
print("Average:", np.mean(arr1))

# Maximum element
print("Max:", np.max(arr1))

# Minimum element
print("Min:", np.min(arr1))

Sum: 21
Average: 3.5
Max: 6
Min: 1


In [12]:
# Aggregating columns

# Sum of elements
print("Sum:", np.sum(arr1, axis=0))

# Average of elements
print("Average:", np.mean(arr1, axis=0))

# Maximum element
print("Max:", np.max(arr1, axis=0))

# Minimum element
print("Min:", np.min(arr1, axis=0))

Sum: [5 7 9]
Average: [2.5 3.5 4.5]
Max: [4 5 6]
Min: [1 2 3]


In [13]:
# Aggregating rows

# Sum of elements
print("Sum:", np.sum(arr1, axis=1))

# Average of elements
print("Average:", np.mean(arr1, axis=1))

# Maximum element
print("Max:", np.max(arr1, axis=1))

# Minimum element
print("Min:", np.min(arr1, axis=1))

Sum: [ 6 15]
Average: [2. 5.]
Max: [3 6]
Min: [1 4]


##### Array reshaping

In [14]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1)
print('Shape : {}'.format(arr1.shape))

[[1 2 3]
 [4 5 6]]
Shape : (2, 3)


In [15]:
# Transpose
arr2 = arr1.T
print(arr2)
print('Shape : {}'.format(arr2.shape))

[[1 4]
 [2 5]
 [3 6]]
Shape : (3, 2)


In [16]:
# Custom reshape
arr3 = np.reshape(arr1, newshape=(3, 2))
print(arr3)
print('Shape : {}'.format(arr3.shape))

[[1 2]
 [3 4]
 [5 6]]
Shape : (3, 2)


In [17]:
arr4 = np.array([1,2,3,4])
print(arr4)
print('Shape : {}'.format(arr4.shape))


[1 2 3 4]
Shape : (4,)


In [18]:
# Add new dimension at the beggining of the shape
arr5 = np.expand_dims(arr4, axis=0)
print(arr5)
print('Shape : {}'.format(arr5.shape))

[[1 2 3 4]]
Shape : (1, 4)


In [19]:
# Add new dimension at the end of the shape
arr6 = np.expand_dims(arr4, axis=1)
print(arr6)
print('Shape : {}'.format(arr6.shape))

[[1]
 [2]
 [3]
 [4]]
Shape : (4, 1)


In [20]:
arr7 = np.squeeze(arr6)
print(arr7)
print('Shape : {}'.format(arr7.shape))

[1 2 3 4]
Shape : (4,)


In [21]:
arr8 = np.squeeze(arr5)
print(arr8)
print('Shape : {}'.format(arr8.shape))

[1 2 3 4]
Shape : (4,)


### Summary

We have learned about:

- Operations on 1-D and 2-D arrays

- Array reshaping