<a href="https://colab.research.google.com/github/spencer18001/Clustering-And-Dimensionality-Reduction---Deep-Dive/blob/main/03/0308.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Operations between numpy arrays

### Operations between numpy arrays having same shape

In [ ]:
import numpy as np

In [ ]:
# 1D case

arr1 = np.array([1, 2, 3, 4, 5, 6, 8])
arr2 = np.array([6, 7, 8, 9, 10, 11,12])

# Addition
print("Addition:", arr1 + arr2)

# Subtraction
print("Subtraction:", arr2 - arr1)

# Multiplication
print("Multiplication:", arr1 * arr2)

# Division
print("Division:", arr2 / arr1)

Addition: [ 7  9 11 13 15 17 20]
Subtraction: [5 5 5 5 5 5 4]
Multiplication: [ 6 14 24 36 50 66 96]
Division: [6.         3.5        2.66666667 2.25       2.         1.83333333
 1.5       ]


In [ ]:
# 2D case

arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Addition
print("Addition:\n", arr1 + arr2)

# Subtraction
print("Subtraction:\n", arr2 - arr1)

# Multiplication
print("Multiplication:\n", arr1 * arr2)

# Division
print("Division:\n", arr2 / arr1)

Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[6 6 6]
 [6 6 6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]


### Broadcasting

#### Broadcasting 1-D arrays


In [ ]:
# Simplest case - 1D
# In order for this broadcast to work, dimension of arr2 must be 1

arr1 = np.array([1, 2, 3])
arr2 = np.array([1])

print('Arr 1 : \n {}'.format(arr1))
print('Arr 2 : \n {}'.format(arr2))

arr1 + arr2

Arr 1 : 
 [1 2 3]
Arr 2 : 
 [1]


array([2, 3, 4])

In [ ]:
# If dimension of arr1 is not 1, we get error

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2])

print('Arr 1 : \n {}'.format(arr1))
print('Arr 2 : \n {}'.format(arr2))

arr1 + arr2

Arr 1 : 
 [1 2 3 4]
Arr 2 : 
 [1 2]


ValueError: operands could not be broadcast together with shapes (4,) (2,) 

##### Broadcasting 2-D arrays

In [ ]:
arr1 = np.array([[1, 2, 3], [4,5,6]])
arr2 = np.array([[1, 2, 3]])

print('Arr 1 : \n {}'.format(arr1))
print('Arr 2 : \n {}'.format(arr2))

arr1 + arr2

Arr 1 : 
 [[1 2 3]
 [4 5 6]]
Arr 2 : 
 [[1 2 3]]


array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
arr1 = np.array([[1, 2, 3], [4,5,6]])
arr2 = np.array([[1], [2]])

print('Arr 1 : \n {}'.format(arr1))
print('Arr 2 : \n {}'.format(arr2))

arr1 + arr2

Arr 1 : 
 [[1 2 3]
 [4 5 6]]
Arr 2 : 
 [[1]
 [2]]


array([[2, 3, 4],
       [6, 7, 8]])

In [ ]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5], [6]])

print('Arr 1 : \n {}'.format(arr1))
print('Arr 2 : \n {}'.format(arr2))

arr1 + arr2

Arr 1 : 
 [[1 2 3]]
Arr 2 : 
 [[4]
 [5]
 [6]]


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

##### Broadcasting arrays of different shappes

In [ ]:
arr1 = np.array([[1, 2, 3], [4,5,6]])
arr2 = np.array([1, 2, 3])

print('Arr 1 : \n {}'.format(arr1))
print('Arr 2 : \n {}'.format(arr2))

arr1 + arr2

Arr 1 : 
 [[1 2 3]
 [4 5 6]]
Arr 2 : 
 [1 2 3]


array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
arr1 = np.array([[1, 2],[3,4], [5,6]])
arr2 = np.array([1, 2, 3]) # broadcasting 是從頭開始塞維度

print('Arr 1 : \n {}'.format(arr1))
print('Arr 2 : \n {}'.format(arr2))

arr1 + arr2

Arr 1 : 
 [[1 2]
 [3 4]
 [5 6]]
Arr 2 : 
 [1 2 3]


ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [ ]:
arr1 + np.expand_dims(arr2, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

### Summary

We have learned about:

- Numpy array broadcasting