<a href="https://colab.research.google.com/github/spencer18001/Clustering-And-Dimensionality-Reduction---Deep-Dive/blob/main/0311.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Working with matrices

#### Lecture agenda

- Creating matrices
- Matrix adition and multiplication

##### Creating matrices

In [1]:
import numpy as np

In [2]:
# Custom matrix

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
# Zero matrix

zero_matrix = np.zeros((3, 3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# Identity matrix

identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# Matrix of ones

ones_matrix = np.ones((3, 3))
print(ones_matrix)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# Random matrix
# np.random.random: Return random floats in the half-open interval [0.0, 1.0).

random_matrix = np.random.random((3, 3))
random_matrix

array([[0.90565692, 0.28869347, 0.10255652],
       [0.34841414, 0.43470568, 0.4388235 ],
       [0.69353211, 0.1378665 , 0.30396029]])

##### Matrix operations

In [7]:
# Matrix addition

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('Mat 1 : \n {}'.format(a))
print('Mat 2 : \n {}'.format(b))

c = a + b
c

Mat 1 : 
 [[1 2]
 [3 4]]
Mat 2 : 
 [[5 6]
 [7 8]]


array([[ 6,  8],
       [10, 12]])

Matrix multiplication

![](https://github.com/spencer18001/Clustering-And-Dimensionality-Reduction---Deep-Dive/blob/main/imgs/mat_mul.png?raw=1)

Source: https://commons.wikimedia.org/wiki/File:Matrix_multiplication_diagram.svg

In [8]:
# Matrix multiplication

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print('Mat 1 : \n {}'.format(a))
print('Mat 2 : \n {}'.format(b))

c = a @ b
c

Mat 1 : 
 [[1 2]
 [3 4]]
Mat 2 : 
 [[5 6]
 [7 8]]


array([[19, 22],
       [43, 50]])

In [9]:
a*b

array([[ 5, 12],
       [21, 32]])

In [10]:
# Matrix transponse

a = np.array([[1, 2], [3, 4]])

print('Mat 1 : \n {}'.format(a))

b = a.T
b

Mat 1 : 
 [[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])